### ISSUE TITLE
Permissions issue with maps

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_dashboard#30]
@mathew-alex can you please whitelist care_dashboard staging for maps

cc: @nihal467 @developedBySJ

**Comment by mathew-alex** [comment]
<img width="1512" alt="Screenshot 2022-10-10 at 3 44 57 PM" src="https://user-images.githubusercontent.com/22002072/194844087-78e6328d-855f-41df-b1dc-42f7e048d0c9.png">

whitelisted care dashboard staging
